// Modernizr 2.6.1 http://modernizr.com/download/#-csstransforms-testprop-testallprops-domprefixes
;window.Modernizr=function(a,b,c){function w(a){i.cssText=a}function x(a,b){return w(prefixes.join(a+";")+(b||""))}function y(a,b){return typeof a===b}function z(a,b){return!!~(""+a).indexOf(b)}function A(a,b){for(var d in a){var e=a[d];if(!z(e,"-")&&i[e]!==c)return b=="pfx"?e:!0}return!1}function B(a,b,d){for(var e in a){var f=b[a[e]];if(f!==c)return d===!1?a[e]:y(f,"function")?f.bind(d||b):f}return!1}function C(a,b,c){var d=a.charAt(0).toUpperCase()+a.slice(1),e=(a+" "+m.join(d+" ")+d).split(" ");return y(b,"string")||y(b,"undefined")?A(e,b):(e=(a+" "+n.join(d+" ")+d).split(" "),B(e,b,c))}var d="2.6.1",e={},f=b.documentElement,g="modernizr",h=b.createElement(g),i=h.style,j,k={}.toString,l="Webkit Moz O ms",m=l.split(" "),n=l.toLowerCase().split(" "),o={},p={},q={},r=[],s=r.slice,t,u={}.hasOwnProperty,v;!y(u,"undefined")&&!y(u.call,"undefined")?v=function(a,b){return u.call(a,b)}:v=function(a,b){return b in a&&y(a.constructor.prototype[b],"undefined")},Function.prototype.bind||(Function.prototype.bind=function(b){var c=this;if(typeof c!="function")throw new TypeError;var d=s.call(arguments,1),e=function(){if(this instanceof e){var a=function(){};a.prototype=c.prototype;var f=new a,g=c.apply(f,d.concat(s.call(arguments)));return Object(g)===g?g:f}return c.apply(b,d.concat(s.call(arguments)))};return e}),o.csstransforms=function(){return!!C("transform")};for(var D in o)v(o,D)&&(t=D.toLowerCase(),e[t]=o[D](),r.push((e[t]?"":"no-")+t));return e.addTest=function(a,b){if(typeof a=="object")for(var d in a)v(a,d)&&e.addTest(d,a[d]);else{a=a.toLowerCase();if(e[a]!==c)return e;b=typeof b=="function"?b():b,enableClasses&&(f.className+=" "+(b?"":"no-")+a),e[a]=b}return e},w(""),h=j=null,e._version=d,e._domPrefixes=n,e._cssomPrefixes=m,e.testProp=function(a){return A([a])},e.testAllProps=C,e}(this,this.document);
// https://github.com/jussi-kalliokoski/jQuery.grab 2012.08.06
(function($){var extend=$.extend,mousedown='mousedown',mousemove='mousemove',mouseup='mouseup',touchstart='touchstart',touchmove='touchmove',touchend='touchend',touchcancel='touchcancel';function unbind(elem,type,func){if(type.substr(0,5)!=='touch'){return $(elem).unbind(type,func);}
var fnc,i;for(i=0;i<bind._binds.length;i++){if(bind._binds[i].elem===elem&&bind._binds[i].type===type&&bind._binds[i].func===func){if(document.addEventListener){elem.removeEventListener(type,bind._binds[i].fnc,false);}else{elem.detachEvent('on'+type,bind._binds[i].fnc);}
bind._binds.splice(i--,1);}}}
function bind(elem,type,func,pass){if(type.substr(0,5)!=='touch'){return $(elem).bind(type,pass,func);}
var fnc,i;if(bind[type]){return bind[type].bind(elem,type,func,pass);}
fnc=function(e){if(!e){e=window.event;}
if(!e.stopPropagation){e.stopPropagation=function(){this.cancelBubble=true;};}
e.data=pass;func.call(elem,e);};if(document.addEventListener){elem.addEventListener(type,fnc,false);}else{elem.attachEvent('on'+type,fnc);}
bind._binds.push({elem:elem,type:type,func:func,fnc:fnc});}
function grab(elem,options)
{var data={move:{x:0,y:0},offset:{x:0,y:0},position:{x:0,y:0},start:{x:0,y:0},affects:document.documentElement,stopPropagation:false,preventDefault:true,touch:true};extend(data,options);data.element=elem;bind(elem,mousedown,mouseDown,data);if(data.touch){bind(elem,touchstart,touchStart,data);}}
function ungrab(elem){unbind(elem,mousedown,mousedown);}
function mouseDown(e){e.data.position.x=e.pageX;e.data.position.y=e.pageY;e.data.start.x=e.pageX;e.data.start.y=e.pageY;e.data.event=e;if(e.data.onstart&&e.data.onstart.call(e.data.element,e.data)){return;}
if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.stopPropagation){e.stopPropagation();}
bind(e.data.affects,mousemove,mouseMove,e.data);bind(e.data.affects,mouseup,mouseUp,e.data);}
function mouseMove(e){if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.preventDefault){e.stopPropagation();}
e.data.move.x=e.pageX-e.data.position.x;e.data.move.y=e.pageY-e.data.position.y;e.data.position.x=e.pageX;e.data.position.y=e.pageY;e.data.offset.x=e.pageX-e.data.start.x;e.data.offset.y=e.pageY-e.data.start.y;e.data.event=e;if(e.data.onmove){e.data.onmove.call(e.data.element,e.data);}}
function mouseUp(e){if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.stopPropagation){e.stopPropagation();}
unbind(e.data.affects,mousemove,mouseMove);unbind(e.data.affects,mouseup,mouseUp);e.data.event=e;if(e.data.onfinish){e.data.onfinish.call(e.data.element,e.data);}}
function touchStart(e){e.data.position.x=e.touches[0].pageX;e.data.position.y=e.touches[0].pageY;e.data.start.x=e.touches[0].pageX;e.data.start.y=e.touches[0].pageY;e.data.event=e;if(e.data.onstart&&e.data.onstart.call(e.data.element,e.data)){return;}
if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.stopPropagation){e.stopPropagation();}
bind(e.data.affects,touchmove,touchMove,e.data);bind(e.data.affects,touchend,touchEnd,e.data);}
function touchMove(e){if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.stopPropagation){e.stopPropagation();}
e.data.move.x=e.touches[0].pageX-e.data.position.x;e.data.move.y=e.touches[0].pageY-e.data.position.y;e.data.position.x=e.touches[0].pageX;e.data.position.y=e.touches[0].pageY;e.data.offset.x=e.touches[0].pageX-e.data.start.x;e.data.offset.y=e.touches[0].pageY-e.data.start.y;e.data.event=e;if(e.data.onmove){e.data.onmove.call(e.data.elem,e.data);}}
function touchEnd(e){if(e.preventDefault&&e.data.preventDefault){e.preventDefault();}
if(e.stopPropagation&&e.data.stopPropagation){e.stopPropagation();}
unbind(e.data.affects,touchmove,touchMove);unbind(e.data.affects,touchend,touchEnd);e.data.event=e;if(e.data.onfinish){e.data.onfinish.call(e.data.element,e.data);}}
bind._binds=[];$.fn.grab=function(a,b){return this.each(function(){return grab(this,a,b);});};$.fn.ungrab=function(a){return this.each(function(){return ungrab(this,a);});};})(jQuery);
// https://github.com/louisremi/jquery.transform.js 2012.08.06
(function($,window,document,Math,undefined){var div=document.createElement("div"),divStyle=div.style,suffix="Transform",testProperties=["O"+suffix,"ms"+suffix,"Webkit"+suffix,"Moz"+suffix],i=testProperties.length,supportProperty,supportMatrixFilter,supportFloat32Array="Float32Array"in window,propertyHook,propertyGet,rMatrix=/Matrix([^)]*)/,rAffine=/^\s*matrix\(\s*1\s*,\s*0\s*,\s*0\s*,\s*1\s*(?:,\s*0(?:px)?\s*){2}\)\s*$/,_transform="transform",_transformOrigin="transformOrigin",_translate="translate",_rotate="rotate",_scale="scale",_skew="skew",_matrix="matrix";while(i--){if(testProperties[i]in divStyle){$.support[_transform]=supportProperty=testProperties[i];$.support[_transformOrigin]=supportProperty+"Origin";continue;}}
if(!supportProperty){$.support.matrixFilter=supportMatrixFilter=divStyle.filter==="";}
$.cssNumber[_transform]=$.cssNumber[_transformOrigin]=true;if(supportProperty&&supportProperty!=_transform){$.cssProps[_transform]=supportProperty;$.cssProps[_transformOrigin]=supportProperty+"Origin";if(supportProperty=="Moz"+suffix){propertyHook={get:function(elem,computed){return(computed?$.css(elem,supportProperty).split("px").join(""):elem.style[supportProperty]);},set:function(elem,value){elem.style[supportProperty]=/matrix\([^)p]*\)/.test(value)?value.replace(/matrix((?:[^,]*,){4})([^,]*),([^)]*)/,_matrix+"$1$2px,$3px"):value;}};}else if(/^1\.[0-5](?:\.|$)/.test($.fn.jquery)){propertyHook={get:function(elem,computed){return(computed?$.css(elem,supportProperty.replace(/^ms/,"Ms")):elem.style[supportProperty]);}};}}else if(supportMatrixFilter){propertyHook={get:function(elem,computed,asArray){var elemStyle=(computed&&elem.currentStyle?elem.currentStyle:elem.style),matrix,data;if(elemStyle&&rMatrix.test(elemStyle.filter)){matrix=RegExp.$1.split(",");matrix=[matrix[0].split("=")[1],matrix[2].split("=")[1],matrix[1].split("=")[1],matrix[3].split("=")[1]];}else{matrix=[1,0,0,1];}
if(!$.cssHooks[_transformOrigin]){matrix[4]=elemStyle?parseInt(elemStyle.left,10)||0:0;matrix[5]=elemStyle?parseInt(elemStyle.top,10)||0:0;}else{data=$._data(elem,"transformTranslate",undefined);matrix[4]=data?data[0]:0;matrix[5]=data?data[1]:0;}
return asArray?matrix:_matrix+"("+matrix+")";},set:function(elem,value,animate){var elemStyle=elem.style,currentStyle,Matrix,filter,centerOrigin;if(!animate){elemStyle.zoom=1;}
value=matrix(value);Matrix=["Matrix("+"M11="+value[0],"M12="+value[2],"M21="+value[1],"M22="+value[3],"SizingMethod='auto expand'"].join();filter=(currentStyle=elem.currentStyle)&&currentStyle.filter||elemStyle.filter||"";elemStyle.filter=rMatrix.test(filter)?filter.replace(rMatrix,Matrix):filter+" progid:DXImageTransform.Microsoft."+Matrix+")";if(!$.cssHooks[_transformOrigin]){if((centerOrigin=$.transform.centerOrigin)){elemStyle[centerOrigin=="margin"?"marginLeft":"left"]=-(elem.offsetWidth/2)+(elem.clientWidth/2)+"px";elemStyle[centerOrigin=="margin"?"marginTop":"top"]=-(elem.offsetHeight/2)+(elem.clientHeight/2)+"px";}
elemStyle.left=value[4]+"px";elemStyle.top=value[5]+"px";}else{$.cssHooks[_transformOrigin].set(elem,value);}}};}
if(propertyHook){$.cssHooks[_transform]=propertyHook;}
propertyGet=propertyHook&&propertyHook.get||$.css;$.fx.step.transform=function(fx){var elem=fx.elem,start=fx.start,end=fx.end,pos=fx.pos,transform="",precision=1E5,i,startVal,endVal,unit;if(!start||typeof start==="string"){if(!start){start=propertyGet(elem,supportProperty);}
if(supportMatrixFilter){elem.style.zoom=1;}
end=end.split("+=").join(start);$.extend(fx,interpolationList(start,end));start=fx.start;end=fx.end;}
i=start.length;while(i--){startVal=start[i];endVal=end[i];unit=+false;switch(startVal[0]){case _translate:unit="px";case _scale:unit||(unit="");transform=startVal[0]+"("+
Math.round((startVal[1][0]+(endVal[1][0]-startVal[1][0])*pos)*precision)/precision+unit+","+
Math.round((startVal[1][1]+(endVal[1][1]-startVal[1][1])*pos)*precision)/precision+unit+")"+
transform;break;case _skew+"X":case _skew+"Y":case _rotate:transform=startVal[0]+"("+
Math.round((startVal[1]+(endVal[1]-startVal[1])*pos)*precision)/precision+"rad)"+
transform;break;}}
fx.origin&&(transform=fx.origin+transform);propertyHook&&propertyHook.set?propertyHook.set(elem,transform,+true):elem.style[supportProperty]=transform;};function matrix(transform){transform=transform.split(")");var
trim=$.trim,i=-1,l=transform.length-1,split,prop,val,prev=supportFloat32Array?new Float32Array(6):[],curr=supportFloat32Array?new Float32Array(6):[],rslt=supportFloat32Array?new Float32Array(6):[1,0,0,1,0,0];prev[0]=prev[3]=rslt[0]=rslt[3]=1;prev[1]=prev[2]=prev[4]=prev[5]=0;while(++i<l){split=transform[i].split("(");prop=trim(split[0]);val=split[1];curr[0]=curr[3]=1;curr[1]=curr[2]=curr[4]=curr[5]=0;switch(prop){case _translate+"X":curr[4]=parseInt(val,10);break;case _translate+"Y":curr[5]=parseInt(val,10);break;case _translate:val=val.split(",");curr[4]=parseInt(val[0],10);curr[5]=parseInt(val[1]||0,10);break;case _rotate:val=toRadian(val);curr[0]=Math.cos(val);curr[1]=Math.sin(val);curr[2]=-Math.sin(val);curr[3]=Math.cos(val);break;case _scale+"X":curr[0]=+val;break;case _scale+"Y":curr[3]=val;break;case _scale:val=val.split(",");curr[0]=val[0];curr[3]=val.length>1?val[1]:val[0];break;case _skew+"X":curr[2]=Math.tan(toRadian(val));break;case _skew+"Y":curr[1]=Math.tan(toRadian(val));break;case _matrix:val=val.split(",");curr[0]=val[0];curr[1]=val[1];curr[2]=val[2];curr[3]=val[3];curr[4]=parseInt(val[4],10);curr[5]=parseInt(val[5],10);break;}
rslt[0]=prev[0]*curr[0]+prev[2]*curr[1];rslt[1]=prev[1]*curr[0]+prev[3]*curr[1];rslt[2]=prev[0]*curr[2]+prev[2]*curr[3];rslt[3]=prev[1]*curr[2]+prev[3]*curr[3];rslt[4]=prev[0]*curr[4]+prev[2]*curr[5]+prev[4];rslt[5]=prev[1]*curr[4]+prev[3]*curr[5]+prev[5];prev=[rslt[0],rslt[1],rslt[2],rslt[3],rslt[4],rslt[5]];}
return rslt;}
function unmatrix(matrix){var
scaleX,scaleY,skew,A=matrix[0],B=matrix[1],C=matrix[2],D=matrix[3];if(A*D-B*C){scaleX=Math.sqrt(A*A+B*B);A/=scaleX;B/=scaleX;skew=A*C+B*D;C-=A*skew;D-=B*skew;scaleY=Math.sqrt(C*C+D*D);C/=scaleY;D/=scaleY;skew/=scaleY;if(A*D<B*C){A=-A;B=-B;skew=-skew;scaleX=-scaleX;}}else{scaleX=scaleY=skew=0;}
return[[_translate,[+matrix[4],+matrix[5]]],[_rotate,Math.atan2(B,A)],[_skew+"X",Math.atan(skew)],[_scale,[scaleX,scaleY]]];}
function interpolationList(start,end){var list={start:[],end:[]},i=-1,l,currStart,currEnd,currType;(start=="none"||isAffine(start))&&(start="");(end=="none"||isAffine(end))&&(end="");if(start&&end&&!end.indexOf("matrix")&&toArray(start).join()==toArray(end.split(")")[0]).join()){list.origin=start;start="";end=end.slice(end.indexOf(")")+1);}
if(!start&&!end){return;}
if(!start||!end||functionList(start)==functionList(end)){start&&(start=start.split(")"))&&(l=start.length);end&&(end=end.split(")"))&&(l=end.length);while(++i<l-1){start[i]&&(currStart=start[i].split("("));end[i]&&(currEnd=end[i].split("("));currType=$.trim((currStart||currEnd)[0]);append(list.start,parseFunction(currType,currStart?currStart[1]:0));append(list.end,parseFunction(currType,currEnd?currEnd[1]:0));}}else{list.start=unmatrix(matrix(start));list.end=unmatrix(matrix(end))}
return list;}
function parseFunction(type,value){var
defaultValue=+(!type.indexOf(_scale)),scaleX,cat=type.replace(/e[XY]/,"e");switch(type){case _translate+"Y":case _scale+"Y":value=[defaultValue,value?parseFloat(value):defaultValue];break;case _translate+"X":case _translate:case _scale+"X":scaleX=1;case _scale:value=value?(value=value.split(","))&&[parseFloat(value[0]),parseFloat(value.length>1?value[1]:type==_scale?scaleX||value[0]:defaultValue+"")]:[defaultValue,defaultValue];break;case _skew+"X":case _skew+"Y":case _rotate:value=value?toRadian(value):0;break;case _matrix:return unmatrix(value?toArray(value):[1,0,0,1,0,0]);break;}
return[[cat,value]];}
function isAffine(matrix){return rAffine.test(matrix);}
function functionList(transform){return transform.replace(/(?:\([^)]*\))|\s/g,"");}
function append(arr1,arr2,value){while(value=arr2.shift()){arr1.push(value);}}
function toRadian(value){return~value.indexOf("deg")?parseInt(value,10)*(Math.PI*2/360):~value.indexOf("grad")?parseInt(value,10)*(Math.PI/200):parseFloat(value);}
function toArray(matrix){matrix=/([^,]*),([^,]*),([^,]*),([^,]*),([^,p]*)(?:px)?,([^)p]*)(?:px)?/.exec(matrix);return[matrix[1],matrix[2],matrix[3],matrix[4],matrix[5],matrix[6]];}
$.transform={centerOrigin:"margin"};})(jQuery,window,document,Math);
// https://github.com/Adios/circleplayer
var CirclePlayer=function(jPlayerSelector,media,options){var self=this,defaults={volume:0.6,supplied:"m4a, oga",cssSelectorAncestor:"#cp_container_1",cssSelector:{play:".cp-play",pause:".cp-pause"}},cssSelector={progressHolder:".cp-progress-holder",progress1:".cp-progress-1",progress2:".cp-progress-2",circleControl:".cp-circle-control"};this.cssClass={gt50:"cp-gt50",fallback:"cp-fallback"};this.spritePitch=104;this.spriteRatio=0.24;this.player=$(jPlayerSelector);this.media=$.extend({},media);this.options=$.extend(true,{},defaults,options);this.cssTransforms=Modernizr.csstransforms;this.audio={};this.eventNamespace=".CirclePlayer";this.jq={};$.each(cssSelector,function(entity,cssSel){self.jq[entity]=$(self.options.cssSelectorAncestor+" "+cssSel);});this._initSolution();this._initPlayer();};CirclePlayer.prototype={_createHtml:function(){},_initPlayer:function(){var self=this;this.player.jPlayer(this.options);this.player.bind($.jPlayer.event.volumechange+this.eventNamespace,function(event){self._volumeupdate(event.jPlayer.options.volume*100);});this.player.bind($.jPlayer.event.ready+this.eventNamespace,function(event){if(event.jPlayer.html.used&&event.jPlayer.html.audio.available){self.audio=$(this).data("jPlayer").htmlElement.audio;}
$(this).jPlayer("setMedia",self.media);self._initCircleControl();self.player.jPlayer('volume',0.1);self.player.jPlayer('volume',self.options.volume);});this.player.bind($.jPlayer.event.play+this.eventNamespace,function(event){$(this).jPlayer("pauseOthers");});},_initSolution:function(){if(this.cssTransforms){this.jq.progressHolder.show().removeClass(this.cssClass.gt50);this.jq.progress1.css({'transform':'rotate(0deg)'});this.jq.progress2.css({'transform':'rotate(0deg)'}).hide();}
else{this.jq.progressHolder.addClass(this.cssClass.gt50).show();this.jq.progress1.addClass(this.cssClass.fallback).progress1.css('background-position','0 '+this.spritePitch+'px');this.jq.progress2.hide();}},_initCircleControl:function(){var self=this;this.jq.circleControl.grab({onmove:function(event){var pc=self._getArcPercent(event.position.x,event.position.y);self.player.jPlayer('volume',Math.round(pc)/100);}});},_volumeupdate:function(percent){var degs=percent*3.6+"deg";var spriteOffset=(Math.floor((Math.round(percent))*this.spriteRatio)-1)*-this.spritePitch;if(percent<=50){if(this.cssTransforms){this.jq.progressHolder.removeClass(this.cssClass.gt50);this.jq.progress1.css({'transform':'rotate('+degs+')'});this.jq.progress2.hide();}else{this.jq.progress1.css('background-position','0 '+spriteOffset+'px');}}else if(percent<=100){if(this.cssTransforms){this.jq.progressHolder.addClass(this.cssClass.gt50);this.jq.progress1.css({'transform':'rotate(180deg)'});this.jq.progress2.css({'transform':'rotate('+degs+')'});this.jq.progress2.show();}else{this.jq.progress1.css('background-position','0 '+spriteOffset+'px');}}},_getArcPercent:function(pageX,pageY){var offset=this.jq.circleControl.offset(),x=pageX-offset.left-this.jq.circleControl.width()/2,y=pageY-offset.top-this.jq.circleControl.height()/2,theta=Math.atan2(y,x);if(theta>-1*Math.PI&&theta<-0.5*Math.PI){theta=2*Math.PI+theta;}
return(theta+Math.PI/2)/2*Math.PI*10;},setMedia:function(media){this.media=$.extend({},media);this.player.jPlayer("setMedia",this.media);},play:function(time){this.player.jPlayer("play",time);},pause:function(time){this.player.jPlayer("pause",time);},destroy:function(){this.player.unbind(this.eventNamespace);this.player.jPlayer("destroy");}};
